## node configurations
node:
  ## the type of crust, for example: authority, full
  chain: "authority"
  ## enable or disable sworker
  sworker: "enable"
  ## enable or disable smanager
  smanager: "disable"
  ## enable or disable ipfs
  ipfs: "disable"

## identity configurations
identity:
  ## the backup of chain controller account
  backup: ''
  ## the password of chain controller account
  password: ""

## chain configurations
chain:
  ## the name of chain node
  name: "crust-node"
